# Docs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  # Enable version updates for npm, (pnpm, yarn also included with `npm` value).
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory.
    directory: '/'
    # Check the npm registry for updates every day (weekdays).
    schedule:
      interval: 'weekly'
    versioning-strategy: 'auto'
    # Ignore major version updates for specific dependencies; add more entries as needed.
    ignore:
      - dependency-name: 'tailwind-merge'
        update-types:
          - 'version-update:semver-major'
