publicHoistPattern:
  - '*@heroui/*'
  - '*eslint*'
  - '*prettier*'
engineStrict: true
allowBuilds:
  '@heroui/shared-utils': true
  '@sentry/cli': true
  '@vercel/speed-insights': true
  bcrypt: true
  esbuild: true
  oxc-resolver: true
  sharp: true
  unrs-resolver: true
pmOnFail: download
minimumReleaseAgeExclude:
  - eslint-plugin-tailwindcss@4.0.3
