export const enum CURRENCY_NAME {
  UAH = 'Ukrainian Hryvnia',
  USD = 'United States Dollar',
  EUR = 'Euro',
  GBP = 'British Pound',
  CAD = 'Canadian Dollar',
  AED = 'United Arab Emirates Dirham',
  INR = 'Indian Rupee',
  IDR = 'Indonesian Rupiah',
  BRL = 'Brazilian Real',
  HKD = 'Hong Kong Dollar',
  CNY = 'Chinese Yuan',
  HUF = 'Hungarian Forint',
  PLN = 'Polish Zloty',
}
export const enum CURRENCY_CODE {
  UAH = 'UAH',
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  CAD = 'CAD',
  AED = 'AED',
  INR = 'INR',
  IDR = 'IDR',
  BRL = 'BRL',
  HKD = 'HKD',
  CNY = 'CNY',
  HUF = 'HUF',
  PLN = 'PLN',
}
export const enum CURRENCY_SIGN {
  UAH = '₴',
  USD = '$',
  EUR = '€',
  GBP = '£',
  CAD = 'C$',
  AED = 'د.إ',
  INR = '₹',
  IDR = 'Rp',
  BRL = 'R$',
  HKD = 'HK$',
  CNY = '¥',
  HUF = 'Ft',
  PLN = 'zł',
}

// Alphabetically sorted.
export const CURRENCIES_LIST: { name: CURRENCY_NAME; code: CURRENCY_CODE }[] = [
  { name: CURRENCY_NAME.UAH, code: CURRENCY_CODE.UAH },
  { name: CURRENCY_NAME.USD, code: CURRENCY_CODE.USD },
  { name: CURRENCY_NAME.EUR, code: CURRENCY_CODE.EUR },
  { name: CURRENCY_NAME.GBP, code: CURRENCY_CODE.GBP },
  { name: CURRENCY_NAME.CAD, code: CURRENCY_CODE.CAD },
  { name: CURRENCY_NAME.AED, code: CURRENCY_CODE.AED },
  { name: CURRENCY_NAME.INR, code: CURRENCY_CODE.INR },
  { name: CURRENCY_NAME.IDR, code: CURRENCY_CODE.IDR },
  { name: CURRENCY_NAME.BRL, code: CURRENCY_CODE.BRL },
  { name: CURRENCY_NAME.HKD, code: CURRENCY_CODE.HKD },
  { name: CURRENCY_NAME.CNY, code: CURRENCY_CODE.CNY },
  { name: CURRENCY_NAME.HUF, code: CURRENCY_CODE.HUF },
  { name: CURRENCY_NAME.PLN, code: CURRENCY_CODE.PLN },
].toSorted((a, b) => a.name.localeCompare(b.name))
