# name: Check
# on:
#   workflow_dispatch:
#   pull_request:
#     types:
#       - opened
#       - synchronize
#   push:
#     branches:
#       - main
# jobs:
#   lint:
#     name: ESLint and TypeScript
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: lts/*

#       - name: Set up latest Yarn
#         uses: threeal/setup-yarn-action@v2.0.0
#         with:
#           version: latest
#           cache: true

#       - name: Check ESLint
#         run: yarn lint

#       - name: Check TypeScript
#         run: yarn typecheck
#   test:
#     name: Tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: lts/*

#       - name: Set up latest Yarn
#         uses: threeal/setup-yarn-action@v2.0.0
#         with:
#           version: latest
#           cache: true

#       - name: Check Tests
#         run: yarn test
